// Generated by CoffeeScript 1.3.1
(function() {

  Ext.define('Portal.ui.Placeholder', {
    extend: 'Ext.Panel',
    xtype: 'placeholder',
    config: {
      baseCls: 'placeholder'
    }
  });

}).call(this);
